stages:
  - deploy

Deploy Docker:
  only:
    - master
  stage: deploy
  script:
    - docker-compose -f "dkc-prod.yml" down
    - docker-compose -f "dkc-prod.yml" up -d
    - docker-compose -f "dkc-prod.yml" addgroup -S docker && adduser -S gitlab-runner -G docker
    - docker-compose -f "dkc-prod.yml" run --user="gitlab-runner" web yarn build
    - pwd