stages:
  - deploy

Deploy Docker:
  only:
    - master
  stage: deploy
  script:
    - docker-compose -f "dkc-prod.yml" down
    - docker-compose -f "dkc-prod.yml" up -d
    - docker-compose -f "dkc-prod.yml" run --user="1001" web yarn build
    - pwd