stages:
  - deploy

Deploy Docker:
  only:
    - master
  stage: deploy
  script:
    - docker-compose -f "dkc-prod.yml" run app rm -rf dist
    - docker-compose -f "dkc-prod.yml" down
    - docker-compose -f "dkc-prod.yml" up -d 
    - docker-compose -f "dkc-prod.yml" run web yarn build
    - pwd