version: '3'
services:
  nginx: 
    image: nginx
    working_dir: /app
    volumes:
      - .:/app
      - modules:/app/node_modules    
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 85:80
    depends_on:
      - web

  web: 
    image: node:11-alpine
    working_dir: /app
    volumes:
      - .:/app
      - modules:/app/node_modules    
    depends_on:
      - app

  app:
    image: node:11-alpine
    working_dir: /app
    volumes:
      - .:/app
      - modules:/app/node_modules
    env_file: .env
    depends_on:
      - pg
    ports:
      - 3000:3000
    command: node server/app.js

  pg:
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5433:5432

volumes:
  modules:
  pgdata: