version: '3'
services:
  web: 
    image: node:11-alpine
    working_dir: /app
    volumes:
      - .:/app
      - modules:/app/node_modules    
    ports:
      - 8081:8081
    depends_on:
      - app

    command: yarn serve      

  app:
    image: node:11-alpine
    working_dir: /app
    volumes:
      - .:/app
      - modules:/app/node_modules
    env_file: .env
    depends_on:
      - pg
    ports:
      - 3000:3000
    command: yarn nodemon server/app.js

  pg:
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5433:5432

volumes:
  modules:
  pgdata: